# Generated by Django 2.1 on 2020-05-06 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=120)),
                ('degree', models.CharField(max_length=120)),
                ('yearOfGraduation', models.CharField(max_length=120)),
                ('groupNumber', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='GraduationProject',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('gitLink', models.CharField(max_length=120)),
                ('graduation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='alumni.Graduation')),
            ],
        ),
        migrations.AddField(
            model_name='graduation',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.Alumni'),
        ),
    ]
