# Generated by Django 2.1 on 2020-05-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_company_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='alumni.Alumni'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='alumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation', to='alumni.Alumni'),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='graduation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='projects', serialize=False, to='alumni.Graduation'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='alumni.Company'),
        ),
    ]
