# Generated by Django 2.1 on 2020-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20200506_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='image',
            field=models.ImageField(blank=True, upload_to='Alumni'),
        ),
    ]
